name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make
    - name: Run tests
      run: make check
    - name: Publish test output
      uses: actions/upload-artifact@v1
      with:
        name: testout
        path: runtest/test/testout
    - name: Install requirements for coverage
      run: |
        sudo apt install ruby
        sudo gem install bashcov
    - name: Generate code coverage report
      run: make codecov
    - name: Publish code coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: runtest/coverage
    - name: Generate coverage badge from report
      run: |
        sudo apt install xsltproc
        COVERAGE=$(sed -n '/<tbody>/,/<\/tbody>/p;/<\/tbody>/q' runtest/coverage/index.html | xsltproc tools/coverage.xsl -)
        COVERAGE_URLENC=$(echo -n "$COVERAGE" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
        curl -X GET "https://img.shields.io/badge/coverage-${COVERAGE_URLENC}-green" >/tmp/coverage.svg
    - name: Upload coverage badge
      run: |
        git config user.email "ci@nowhere.org"
        git config user.name "ci"
        git checkout --orphan assets || git checkout assets
        git reset --hard
        cp /tmp/coverage.svg .
        git add .
        git commit -m 'Updated coverage badge'
        git push -u origin assets
